<?php

$title = 'Edit User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<form method="post">
	<div class="form-group">
		<label name="fullname">Full Name :<br/>
			 <input type="text" name="fullname" value="<?php echo $user->getFullname(); ?>" class='form-control'>
		</label>
	</div>

	<div class="form-group">
		<input type="submit" value="Submit" class="btn btn-success">		
	</div>  
  
</form>